[package]
name = "MyLang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mylang"
path = "src/main.rs"

[lib]
name = "my"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[[test]]
name = "integration"
path = "tests/mod.rs"
